export const generalRequirements = [
  { id: "UNITS", label: "Total Units (32)", targetCount: 32 },
  { id: "WRIT", label: "First-Year Writing", targetCount: 1 },
  { id: "LANG", label: "Foreign Language", targetCount: 2 },
  { id: "QR", label: "Quantitative Reasoning", targetCount: 1 },
  { id: "300", label: "300-level Courses", targetCount: 4 },
  { id: "PE", label: "Physical Education*", targetCount: 8 },
  { id: "EXP", label: "Experiential Learning", targetCount: 2 },
];

export const distributionRequirements = [
  { id: "GROUP1_TOTAL", label: "Group 1: Humanities & Arts", targetCount: 3 },
  { id: "GROUP2_TOTAL", label: "Group 2: Social Sciences", targetCount: 3 },
  { id: "GROUP3_TOTAL", label: "Group 3: Science & Math", targetCount: 3 },
];

export const internalRequirements = [
  { id: "LL", label: "Language & Literature", targetCount: 1 },
  { id: "ARTS", label: "Visual Arts, Music, Theatre, Film, Video", targetCount: 1 },
  { id: "SBA", label: "Social & Behavioral Analysis", targetCount: 1 },
  { id: "EC", label: "Epistemology & Cognition", targetCount: 1 },
  { id: "REP", label: "Religion, Ethics & Moral Philosophy", targetCount: 1 },
  { id: "HST", label: "Historical Studies", targetCount: 1 },
  { id: "NPS", label: "Natural & Physical Science", targetCount: 1 },
  { id: "MM", label: "Mathematical Modeling", targetCount: 1 },
  { id: "LAB", label: "Laboratory Course", targetCount: 1 },
];

export const seedRequirements = [...generalRequirements, ...distributionRequirements];

export const requirementTagOptions = [
  { id: "WRIT", label: "WRIT" },
  { id: "LANG", label: "LANG" },
  { id: "QR", label: "QR" },
  { id: "DL", label: "DL" },
  { id: "LL", label: "LL" },
  { id: "ARTS", label: "ARTS" },
  { id: "SBA", label: "SBA" },
  { id: "EC", label: "EC" },
  { id: "HST", label: "HST" },
  { id: "REP", label: "REP" },
  { id: "MM", label: "MM" },
  { id: "NPS", label: "NPS" },
  { id: "LAB", label: "LAB" },
  { id: "300", label: "300" },
  { id: "PE", label: "PE" },
  { id: "EXP", label: "EXP" },
];

export const subjectOptions = [
  "Africana Studies",
  "American Studies",
  "Anthropology",
  "Arabic",
  "Architecture",
  "Art History",
  "Art-Studio",
  "Astronomy",
  "Astrophysics",
  "Biochemistry",
  "Biological Sciences",
  "Calderwood Seminars in Public Writing",
  "Chemical Physics",
  "Chemistry",
  "Chinese Language and Culture",
  "Cinema and Media Studies",
  "Classical Civilization",
  "Classics",
  "Cognitive and Linguistic Sciences",
  "Comparative Literature",
  "Comparative Race and Ethnicity",
  "Computer Science",
  "Data Science",
  "East Asian Languages and Cultures",
  "Economics",
  "Education",
  "Engineering",
  "English",
  "Environmental Studies",
  "Extradepartmental",
  "French",
  "Geosciences",
  "German",
  "Greek",
  "Hindi/Urdu",
  "History",
  "Italian Studies",
  "Japanese Language and Culture",
  "Jewish Studies",
  "Korean Language and Culture",
  "Latin",
  "Latin American Studies",
  "Linguistics",
  "Mathematics",
  "Media Arts & Sciences",
  "Medieval/Renaissance Studies",
  "Middle Eastern Studies",
  "Music",
  "Neuroscience",
  "Peace and Justice Studies",
  "Philosophy",
  "Physical Education",
  "Physics",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Quantitative Reasoning",
  "Religion",
  "Russian",
  "Sociology",
  "South Asia Studies",
  "Spanish",
  "Statistics",
  "Theatre Studies",
  "Women's and Gender Studies",
  "Writing",
];

export const courseCodeToDepartment = {
  AFR: "Africana Studies",
  AMST: "American Studies",
  ANTH: "Anthropology",
  ARAB: "Arabic",
  ARCH: "Architecture",
  ARTH: "Art History",
  ARTS: "Art-Studio",
  ASTR: "Astronomy",
  BIOC: "Biochemistry",
  BIOL: "Biological Sciences",
  BISC: "Biological Sciences",
  CAMS: "Cinema and Media Studies",
  CHEM: "Chemistry",
  CHIN: "Chinese Language and Culture",
  CLCV: "Classical Civilization",
  CLSC: "Cognitive and Linguistic Sciences",
  COGS: "Cognitive and Linguistic Sciences",
  CPLT: "Comparative Literature",
  CS: "Computer Science",
  DS: "Data Science",
  EALC: "East Asian Languages and Cultures",
  ECON: "Economics",
  EDUC: "Education",
  EDST: "Education",
  ENGR: "Engineering",
  ENG: "English",
  ENGL: "English",
  ENVS: "Environmental Studies",
  ES: "Environmental Studies",
  EXTD: "Extradepartmental",
  FREN: "French",
  GEOS: "Geosciences",
  GER: "German",
  GRK: "Greek",
  GRMN: "German",
  HNUR: "Hindi/Urdu",
  HIST: "History",
  ITAL: "Italian Studies",
  ITAS: "Italian Studies",
  JAPN: "Japanese Language and Culture",
  JPN: "Japanese Language and Culture",
  JWST: "Jewish Studies",
  KOR: "Korean Language and Culture",
  LANG: "Extradepartmental",
  LAST: "Latin American Studies",
  LAT: "Latin",
  LING: "Linguistics",
  MATH: "Mathematics",
  MAS: "Media Arts & Sciences",
  MELA: "Middle Eastern Studies",
  MES: "Middle Eastern Studies",
  MER: "Medieval/Renaissance Studies",
  MUS: "Music",
  NEUR: "Neuroscience",
  PE: "Physical Education",
  PEAC: "Peace and Justice Studies",
  PHIL: "Philosophy",
  PHYS: "Physics",
  POL: "Political Science",
  POLS: "Political Science",
  POL1: "Political Science",
  POL2: "Political Science",
  POL3: "Political Science",
  POL4: "Political Science",
  PORT: "Portuguese",
  PSYC: "Psychology",
  QR: "Quantitative Reasoning",
  REL: "Religion",
  RELI: "Religion",
  RUSS: "Russian",
  SAS: "South Asia Studies",
  SCI: "Extradepartmental",
  SOC: "Sociology",
  SPAN: "Spanish",
  STAT: "Statistics",
  THST: "Theatre Studies",
  WGST: "Women's and Gender Studies",
  WRIT: "Writing",
};

export const majorRequirements = {
  "Computer Science": {
    description: "Complete Wellesley's full CS core, advanced electives, two 300-level courses, and MATH 225.",
    csStructure: {
      introOptions: ["CS 111", "CS 111M", "CS 111X", "CS 112"],
      coreGroups: [
        { id: "cs230", label: "CS 230 Series", options: ["CS 230", "CS 230P", "CS 230X"] },
        { id: "cs231", label: "CS 231", options: ["CS 231"] },
        { id: "cs235", label: "CS 235", options: ["CS 235"] },
        { id: "cs240", label: "CS 240", options: ["CS 240"] },
      ],
      level300Required: 2,
      electivesRequired: 2,
      excludedCourses: ["CS 250", "CS 250H", "CS 350", "CS 350H", "CS 360", "CS 370"],
      mathRequirements: ["MATH 225"],
    },
  },
  Mathematics: {
    unitTarget: 10,
    requiredCourses: ["MATH 115", "MATH 116", "MATH 205", "MATH 206", "MATH 302", "MATH 305"],
    electiveCourses: 2,
    description:
      "Mathematics majors build computational fluency, extend concepts to new contexts, represent real-world patterns with mathematical structures, communicate precise arguments, and appreciate math as an evolving, creative discipline. The major includes calculus (MATH 115 plus MATH 116 or MATH 120), the 200-level linear algebra/advanced calculus pair (MATH 205 and MATH 206), the 300-level algebra/analysis duo (MATH 302 and MATH 305), and at least two additional 300-level MATH units (excluding independent study). Across the plan you must accumulate eight MATH/STAT courses at the 200 level or above and deliver the department’s junior/senior presentation.",
    prerequisites:
      "Complete MATH 115 and either MATH 116 or MATH 120 (or equivalent placement) before moving into the 200-level core. Finish prerequisites for MATH 302 and MATH 305 before junior year so the upper-level sequence stays on track.",
    mathStructure: {
      calculusSequence: ["MATH 115", "MATH 116", "MATH 120"],
      coreCourses: ["MATH 205", "MATH 206"],
      seminarCourses: ["MATH 302", "MATH 305"],
      additional300Required: 2,
      advancedTotalRequired: 8,
      allowedDepartments: ["Mathematics", "Statistics"],
      excludedCourses: ["MATH 350", "MATH 360", "MATH 370"],
      presentationNote:
        "Give one classroom or seminar talk during junior or senior year (e.g., student seminar, eligible course, or instructor-approved presentation). Track completion with your advisor.",
    },
  },
  Economics: {
    requiredCourses: ["ECON 101", "ECON 102", "ECON 103", "ECON 201", "ECON 202", "ECON 203"],
    electiveCourses: 3,
    mathRequirements: ["MATH 115"],
    description:
      "Economics majors learn to reason about scarcity, trade-offs, efficiency versus equity, global interdependence, macro stabilization, and long-run growth so they can craft and critique evidence-based policy arguments in writing and speech. The major requires nine ECON units that cover introductory and intermediate microeconomics (ECON 101/101P and ECON 201), introductory and intermediate macroeconomics (ECON 102/102P and ECON 202), the statistics/econometrics sequence (ECON 103 and ECON 203), at least two 300-level ECON courses taken at Wellesley (ordinarily not ECON 350/360/370), and electives that can include QR 260/STAT 260 or QR 309/STAT 309.",
    prerequisites:
      "Complete one semester of calculus at the level of MATH 115 or above before taking ECON 201, ECON 202, or ECON 203. If you replace ECON 103 with STAT 160, STAT 218, PSYC 105, or PSYC 205, add another ECON elective so the major still includes nine ECON units.",
    econStructure: {
      microIntro: ["ECON 101", "ECON 101P"],
      microIntermediate: ["ECON 201"],
      macroIntro: ["ECON 102", "ECON 102P"],
      macroIntermediate: ["ECON 202"],
      statsSequence: ["ECON 103", "ECON 203"],
      mathPrereq: "MATH 115",
      totalCoursesRequired: 9,
      level300Required: 2,
      excluded300: ["ECON 350", "ECON 360", "ECON 370"],
      altStatsCredit: ["STAT 160", "STAT 218", "PSYC 105", "PSYC 205"],
      electiveSubstitutions: ["QR 260", "STAT 260", "QR 309", "STAT 309"],
    },
  },
  English: {
    description: "Ten courses emphasizing literary study, with breadth in historical periods, two 300-level seminars, and postcolonial or ethnic literature.",
    englishStructure: {
      totalRequired: 10,
      deptMinimum: 8,
      upperLevelRequired: 7,
      level300Required: 2,
      postcolonialRequired: 1,
      pre1900Required: 3,
      pre1800Required: 2,
      creativeWritingRequired: 0,
    },
  },
  "English and Creative Writing": {
    description: "Twelve courses blending literary study with four creative writing experiences, plus the same historical and advanced seminar expectations as the English major.",
    englishStructure: {
      totalRequired: 12,
      deptMinimum: 8,
      upperLevelRequired: 9,
      level300Required: 2,
      postcolonialRequired: 1,
      pre1900Required: 3,
      pre1800Required: 2,
      creativeWritingRequired: 4,
    },
  },
  "Biological Sciences": {
    description: "Nine BISC courses with intro/core distributions, two 300-level courses, one elective, plus two CHEM courses.",
    bioStructure: {
      introCell: ["BISC 110", "BISC 110P", "BISC 112", "BISC 112Y", "BISC 116"],
      introOrganismal: ["BISC 111", "BISC 111T", "BISC 113", "BISC 113Y"],
      groupCell: ["BISC 219", "BISC 220"],
      groupSystems: ["BISC 203", "BISC 207", "BISC 216"],
      groupCommunity: ["BISC 201", "BISC 202", "BISC 209", "BISC 210", "BISC 214", "BISC 247", "ES 247"],
      excludedCourses: ["BISC 250", "BISC 250G", "BISC 250H", "BISC 350", "BISC 350H", "BISC 355", "BISC 360", "BISC 365", "BISC 370"],
      additional200Required: 1,
      level300Required: 2,
      electiveRequired: 1,
      electiveAdditionalOptions: ["EXTD 225"],
      chemIntroOptions: ["CHEM 105", "CHEM 105P", "CHEM 116", "CHEM 120"],
      chemAdvancedPrefix: "CHEM",
    },
  },
  Anthropology: {
    description: "Nine ANTH units including ANTH 101, another intro, ANTH 205, ANTH 301, an additional 300-level, electives, and an approved experience.",
    anthroStructure: {
      introRequired: "ANTH 101",
      introSecondOptions: ["ANTH 102", "ANTH 103", "CLCV 103"],
      midRequirement: "ANTH 205",
      seminarRequirement: "ANTH 301",
      extra300Required: 1,
      electiveRequired: 4,
      excludedCourses: ["ANTH 350", "ANTH 360", "ANTH 370"],
      experienceRequired: true,
    },
  },
  "Media Arts and Sciences": {
    unitTarget: 12,
    introductoryCourses: {
      visualAnalysis: ["ARTH 100", "WRIT 107", "CAMS 100"],
      studioFoundation: ["Any 100-level ARTS course"],
      computerScience: ["Any 100-level CS course"],
    },
    coreCourses: {
      studioCore: [
        "ARTS 205",
        "ARTS 207",
        "ARTS 208",
        "ARTS 216",
        "ARTS 219",
        "ARTS 220",
        "ARTS 221",
        "ARTS 222",
        "ARTS 223",
        "ARTS 255",
        "ARTS 260",
        "ARTS 265",
        "ARTS 307",
        "ARTS 308",
        "ARTS 313",
        "ARTS 317H",
        "ARTS 318H",
        "ARTS 321",
        "ARTS 322",
        "ARTS 323",
        "ARTS 336",
        "ARTS 365",
        "ARTS 366",
        "CAMS 301",
        "MUS 275",
        "MUS 277",
      ],
      csCore: [
        "CS 110",
        "CS 111",
        "CS 121",
        "CS 200",
        "CS 204",
        "CS 220",
        "CS 221",
        "CS 230",
        "CS 232",
        "CS 304",
        "CS 307",
        "CS 315",
        "CS 317",
        "CS 320",
        "CS 321",
        "CS 323",
        "CS 325",
        "CS 365",
        "CS 366",
      ],
    },
    capstoneRequired: 1,
    capstoneCourses: ["ARTS 321", "ARTS 322", "ARTS 365", "ARTS 366", "CS 365", "CS 366"],
    mediaCulture: 1,
    advancedProduction: 1,
    portfolioRequired: true,
    description:
      "Interdisciplinary major combining studio arts, computer science, and media culture. Requires 3 intro courses, 6 core courses (3 studio + 3 CS), 1 capstone, and portfolio.",
  },
  "Africana Studies": {
    unitTarget: 9,
    description:
      "Nine-course Africana Studies major anchored by AFR 105 (or AFR 210 for late declarers), with at least two 300-level AFR seminars, attendance at the Africana Colloquium, and a chosen geographic or thematic concentration across the Africana world.",
    afrStructure: {
      introOptions: ["AFR 105", "AFR 210"],
      level300Required: 2,
    },
  },
  "American Studies": {
    unitTarget: 9,
    description:
      "Interdisciplinary major examining the histories and cultures of the United States through American Studies coursework, electives drawn from affiliated departments, and an advisor-approved thematic concentration.",
    amerStructure: {
      introOptions: ["AMST 101", "AMST 121"],
      coreCoursesRequired: 5,
      level300Required: 2,
      electiveCoursesRequired: 3,
    },
  },
  "Custom Major": {
    description:
      "Design an interdepartmental plan that is not covered by Wellesley’s existing majors. An individual major should build cumulative expertise around a clearly described theme, blend theoretical and methodological work, and include at least eight units above the introductory level (minimum four in a single department).",
    prerequisites:
      "Draft the plan with two faculty advisors from different departments and submit it to the Committee on Curriculum and Academic Policy (CCAP) for approval—ideally by sophomore spring. Use the Major Declaration form on MyWellesley once the plan is approved, and route later changes through your advisors and CCAP.",
  },
};
