export const generalRequirements = [
  { id: "UNITS", label: "Total Units (32)", targetCount: 32 },
  { id: "WRIT", label: "First-Year Writing", targetCount: 1 },
  { id: "LANG", label: "Foreign Language", targetCount: 2 },
  { id: "QR", label: "Quantitative Reasoning", targetCount: 1 },
  { id: "300", label: "300-level Courses", targetCount: 4 },
  { id: "PE", label: "Physical Education*", targetCount: 8 },
  { id: "EXP", label: "Experiential Learning", targetCount: 2 },
];

export const distributionRequirements = [
  { id: "GROUP1_TOTAL", label: "Group 1: Humanities & Arts", targetCount: 3 },
  { id: "GROUP2_TOTAL", label: "Group 2: Social Sciences", targetCount: 3 },
  { id: "GROUP3_TOTAL", label: "Group 3: Science & Math", targetCount: 3 },
];

export const internalRequirements = [
  { id: "LL", label: "Language & Literature", targetCount: 1 },
  { id: "ARTS", label: "Visual Arts, Music, Theatre, Film, Video", targetCount: 1 },
  { id: "SBA", label: "Social & Behavioral Analysis", targetCount: 1 },
  { id: "EC", label: "Epistemology & Cognition", targetCount: 1 },
  { id: "REP", label: "Religion, Ethics & Moral Philosophy", targetCount: 1 },
  { id: "HST", label: "Historical Studies", targetCount: 1 },
  { id: "NPS", label: "Natural & Physical Science", targetCount: 1 },
  { id: "MM", label: "Mathematical Modeling", targetCount: 1 },
  { id: "LAB", label: "Laboratory Course", targetCount: 1 },
];

export const seedRequirements = [...generalRequirements, ...distributionRequirements];

export const requirementTagOptions = [
  { id: "WRIT", label: "WRIT" },
  { id: "LANG", label: "LANG" },
  { id: "QR", label: "QR" },
  { id: "DL", label: "DL" },
  { id: "LL", label: "LL" },
  { id: "ARTS", label: "ARTS" },
  { id: "SBA", label: "SBA" },
  { id: "EC", label: "EC" },
  { id: "HST", label: "HST" },
  { id: "REP", label: "REP" },
  { id: "MM", label: "MM" },
  { id: "NPS", label: "NPS" },
  { id: "LAB", label: "LAB" },
  { id: "300", label: "300" },
  { id: "PE", label: "PE" },
  { id: "EXP", label: "EXP" },
];

export const subjectOptions = [
  "Africana Studies",
  "American Studies",
  "Anthropology",
  "Arabic",
  "Architecture",
  "Art History",
  "Art-Studio",
  "Astronomy",
  "Astrophysics",
  "Biochemistry",
  "Biological Sciences",
  "Calderwood Seminars in Public Writing",
  "Chemical Physics",
  "Chemistry",
  "Chinese Language and Culture",
  "Cinema and Media Studies",
  "Classical Civilization",
  "Classics",
  "Cognitive and Linguistic Sciences",
  "Comparative Literature",
  "Comparative Race and Ethnicity",
  "Computer Science",
  "Data Science",
  "East Asian Languages and Cultures",
  "Economics",
  "Education",
  "Engineering",
  "English",
  "Environmental Studies",
  "Extradepartmental",
  "French", 
  "French Cultural Studies",
  "Geosciences",
  "German",
  "German Studies",
  "Greek",
  "Hebrew",
  "Hindi/Urdu",
  "History",
  "Italian Studies",
  "Japanese Language and Culture",
  "Jewish Studies",
  "Korean Language and Culture",
  "Latin",
  "Latin American Studies",
  "Linguistics",
  "Mathematics",
  "Media Arts & Sciences",
  "Medieval/Renaissance Studies",
  "Middle Eastern Studies",
  "Music",
  "Neuroscience",
  "Peace and Justice Studies",
  "Philosophy",
  "Physical Education",
  "Physics",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Quantitative Reasoning",
  "Religion",
  "Russian",
  "Sociology",
  "South Asia Studies",
  "Spanish",
  "Statistics",
  "Theatre Studies",
  "Women's and Gender Studies",
  "Writing",
];

export const courseCodeToDepartment = {
  AFR: "Africana Studies",
  AMST: "American Studies",
  ANTH: "Anthropology",
  ARAB: "Arabic",
  ARCH: "Architecture",
  ARTH: "Art History",
  ARTS: "Art-Studio",
  ASTR: "Astronomy",
  BIOC: "Biochemistry",
  BIOL: "Biological Sciences",
  BISC: "Biological Sciences",
  CAMS: "Cinema and Media Studies",
  CHEM: "Chemistry",
  CHIN: "Chinese Language and Culture",
  CLCV: "Classical Civilization",
  CLSC: "Cognitive and Linguistic Sciences",
  COGS: "Cognitive and Linguistic Sciences",
  CPLT: "Comparative Literature",
  CS: "Computer Science",
  DS: "Data Science",
  EALC: "East Asian Languages and Cultures",
  ECON: "Economics",
  EDUC: "Education",
  EDST: "Education",
  ENGR: "Engineering",
  ENG: "English",
  ENGL: "English",
  ENVS: "Environmental Studies",
  ES: "Environmental Studies",
  EXTD: "Extradepartmental",
  FREN: "French",
  FRST: "French Cultural Studies",
  GEOS: "Geosciences",
  GER: "German",
  GRK: "Greek", 
  GRMN: "German",
  HEBR: "Hebrew",
  HNUR: "Hindi/Urdu",
  HIST: "History",
  ITAS: "Italian Studies",
  JAPN: "Japanese Language and Culture",
  JPN: "Japanese Language and Culture",
  JWST: "Jewish Studies",
  KOR: "Korean Language and Culture",
  LANG: "Extradepartmental",
  LAST: "Latin American Studies",
  LAT: "Latin",
  LING: "Linguistics",
  MATH: "Mathematics",
  MAS: "Media Arts & Sciences",
  MELA: "Middle Eastern Studies",
  MES: "Middle Eastern Studies",
  MER: "Medieval/Renaissance Studies",
  MUS: "Music",
  NEUR: "Neuroscience",
  PE: "Physical Education",
  PEAC: "Peace and Justice Studies",
  PHIL: "Philosophy",
  PHYS: "Physics",
  POL: "Political Science",
  POLS: "Political Science",
  POL1: "Political Science",
  POL2: "Political Science",
  POL3: "Political Science",
  POL4: "Political Science",
  PORT: "Portuguese",
  PSYC: "Psychology",
  QR: "Quantitative Reasoning",
  REL: "Religion",
  RELI: "Religion",
  RUSS: "Russian",
  SAS: "South Asia Studies",
  SCI: "Extradepartmental",
  SOC: "Sociology",
  SPAN: "Spanish",
  STAT: "Statistics",
  THST: "Theatre Studies",
  WGST: "Women's and Gender Studies",
  WRIT: "Writing",
};

export const majorRequirements = {
  "Computer Science": {
    description: "Complete Wellesley's full CS core, advanced electives, two 300-level courses, and MATH 225.",
    csStructure: {
      introOptions: ["CS 111", "CS 111M", "CS 111X", "CS 112"],
      coreGroups: [
        { id: "cs230", label: "CS 230 Series", options: ["CS 230", "CS 230P", "CS 230X"] },
        { id: "cs231", label: "CS 231", options: ["CS 231"] },
        { id: "cs235", label: "CS 235", options: ["CS 235"] },
        { id: "cs240", label: "CS 240", options: ["CS 240"] },
      ],
      level300Required: 2,
      electivesRequired: 2,
      excludedCourses: ["CS 250", "CS 250H", "CS 350", "CS 350H", "CS 360", "CS 370"],
      mathRequirements: ["MATH 225"],
    },
  },
  Mathematics: {
    unitTarget: 10,
    requiredCourses: ["MATH 115", "MATH 116", "MATH 205", "MATH 206", "MATH 302", "MATH 305"],
    electiveCourses: 2,
    description:
      "Mathematics centers on the calculus sequence, the MATH 205/206 core, the MATH 302/305 seminar pair, plus two additional 300-level MATH units while reaching eight advanced MATH/STAT courses and the junior/senior presentation.",
    prerequisites:
      "Complete MATH 115 and either MATH 116 or MATH 120 (or equivalent placement) before moving into the 200-level core. Finish prerequisites for MATH 302 and MATH 305 before junior year so the upper-level sequence stays on track.",
    mathStructure: {
      calculusSequence: ["MATH 115", "MATH 116", "MATH 120"],
      coreCourses: ["MATH 205", "MATH 206"],
      seminarCourses: ["MATH 302", "MATH 305"],
      additional300Required: 2,
      advancedTotalRequired: 8,
      allowedDepartments: ["Mathematics", "Statistics"],
      excludedCourses: ["MATH 350", "MATH 360", "MATH 370"],
      presentationNote:
        "Give one classroom or seminar talk during junior or senior year (e.g., student seminar, eligible course, or instructor-approved presentation). Track completion with your advisor.",
    },
  },
  Economics: {
    requiredCourses: ["ECON 101", "ECON 102", "ECON 103", "ECON 201", "ECON 202", "ECON 203"],
    electiveCourses: 3,
    mathRequirements: ["MATH 115"],
    description:
      "The Economics major spans introductory/intermediate micro and macro, the statistics/econometrics pair, two on-campus 300-level seminars, and electives (including approved QR/STAT substitutes). Plan for nine ECON-coded units total.",
    prerequisites:
      "Complete one semester of calculus at the level of MATH 115 or above before taking ECON 201, ECON 202, or ECON 203. If you replace ECON 103 with STAT 160, STAT 218, PSYC 105, or PSYC 205, add another ECON elective so the major still includes nine ECON units.",
    econStructure: {
      microIntro: ["ECON 101", "ECON 101P"],
      microIntermediate: ["ECON 201"],
      macroIntro: ["ECON 102", "ECON 102P"],
      macroIntermediate: ["ECON 202"],
      statsSequence: ["ECON 103", "ECON 203"],
      mathPrereq: "MATH 115",
      totalCoursesRequired: 9,
      level300Required: 2,
      excluded300: ["ECON 350", "ECON 360", "ECON 370"],
      altStatsCredit: ["STAT 160", "STAT 218", "PSYC 105", "PSYC 205"],
      electiveSubstitutions: ["QR 260", "STAT 260", "QR 309", "STAT 309"],
    },
  },
  English: {
    description: "Ten courses emphasizing literary study, with breadth in historical periods, two 300-level seminars, and postcolonial or ethnic literature.",
    englishStructure: {
      totalRequired: 10,
      deptMinimum: 8,
      upperLevelRequired: 7,
      level300Required: 2,
      postcolonialRequired: 1,
      pre1900Required: 3,
      pre1800Required: 2,
      creativeWritingRequired: 0,
    },
  },
  "English and Creative Writing": {
    description: "Twelve courses blending literary study with four creative writing experiences, plus the same historical and advanced seminar expectations as the English major.",
    englishStructure: {
      totalRequired: 12,
      deptMinimum: 8,
      upperLevelRequired: 9,
      level300Required: 2,
      postcolonialRequired: 1,
      pre1900Required: 3,
      pre1800Required: 2,
      creativeWritingRequired: 4,
    },
  },
  "Biological Sciences": {
    description: "Nine BISC courses with intro/core distributions, two 300-level courses, one elective, plus two CHEM courses.",
    bioStructure: {
      introCell: ["BISC 110", "BISC 110P", "BISC 112", "BISC 112Y", "BISC 116"],
      introOrganismal: ["BISC 111", "BISC 111T", "BISC 113", "BISC 113Y"],
      groupCell: ["BISC 219", "BISC 220"],
      groupSystems: ["BISC 203", "BISC 207", "BISC 216"],
      groupCommunity: ["BISC 201", "BISC 202", "BISC 209", "BISC 210", "BISC 214", "BISC 247", "ES 247"],
      excludedCourses: ["BISC 250", "BISC 250G", "BISC 250H", "BISC 350", "BISC 350H", "BISC 355", "BISC 360", "BISC 365", "BISC 370"],
      additional200Required: 1,
      level300Required: 2,
      electiveRequired: 1,
      electiveAdditionalOptions: ["EXTD 225"],
      chemIntroOptions: ["CHEM 105", "CHEM 105P", "CHEM 116", "CHEM 120"],
      chemAdvancedPrefix: "CHEM",
    },
  },
  Anthropology: {
    description: "Nine ANTH units including ANTH 101, another intro, ANTH 205, ANTH 301, an additional 300-level, electives, and an approved experience.",
    anthroStructure: {
      introRequired: "ANTH 101",
      introSecondOptions: ["ANTH 102", "ANTH 103", "CLCV 103"],
      midRequirement: "ANTH 205",
      seminarRequirement: "ANTH 301",
      extra300Required: 1,
      electiveRequired: 4,
      excludedCourses: ["ANTH 350", "ANTH 360", "ANTH 370"],
      experienceRequired: true,
    },
  },
  Architecture: {
    unitTarget: 11,
    description:
      "Eleven-course plan balancing architectural history, studio design, and allied electives.",
    prerequisites:
      "Select an advisor in your preferred concentration (history or studio) to map the intermediate, advanced, and related coursework.",
    archStructure: {
      totalUnitsRequired: 11,
      foundation: [
        { id: "arch-foundation-intro", label: "Intro art history or writing", options: ["ARTH 100", "WRIT 107"] },
        { id: "arch-foundation-drawing", label: "ARTS 105 Drawing I", options: ["ARTS 105"] },
        { id: "arch-foundation-3d", label: "ARTS 113 3D Design", options: ["ARTS 113"] },
        { id: "arch-gateway", label: "Gateway survey", options: ["ARTH 200", "ARTH 231", "ARTH 228", "ARTS 216"] },
      ],
      intermediateRequired: 2,
      advancedRequired: 2,
      additionalRequired: 2,
      intermediateDepartments: ["Architecture", "Art History", "Art-Studio", "Media Arts & Sciences", "Cinema and Media Studies"],
      advancedDepartments: ["Architecture", "Art History", "Art-Studio", "Media Arts & Sciences"],
      advancedWellesleyDepartments: ["Architecture", "Art History", "Art-Studio"],
      additionalDepartments: [
        "Architecture",
        "Art History",
        "Art-Studio",
        "Media Arts & Sciences",
        "Cinema and Media Studies",
        "Sociology",
        "Anthropology",
        "Philosophy",
        "Women's and Gender Studies",
        "Engineering",
        "Mathematics",
        "Physics",
        "Theatre Studies",
        "Environmental Studies",
      ],
    },
  },
  "Studio Art": {
    unitTarget: 10,
    description:
      "Ten-course studio plan: art history intro, drawing foundation, one additional 100-level studio, a modern/contemporary art history, five 200+ studio courses (two at 300-level), plus the ARTS 317H/318H senior capstone sequence.",
    prerequisites:
      "Complete ARTH 100 or CAMS 101 and the 100-level studio foundations early to unlock upper-level studios and the capstone exhibition.",
    studioStructure: {
      foundation: [
        { id: "studio-arth-intro", label: "ARTH 100 or CAMS 101", options: ["ARTH 100", "CAMS 101"] },
        { id: "studio-drawing", label: "ARTS 105", options: ["ARTS 105"] },
        { id: "studio-100-elective", label: "One additional 100-level studio", options: ["ARTS 108", "CAMS 138", "ARTS 109", "ARTS 110", "ARTS 112", "ARTS 113", "ARTS 115", "WRIT 115", "ARTS 165", "CAMS 135"] },
        { id: "studio-modern-history", label: "20th/21st century art history", options: [] },
      ],
      upperStudioRequired: 5,
      level300Required: 2,
      capstoneCourses: ["ARTS 317H", "ARTS 318H"],
      allowedStudioDepartments: ["Art-Studio", "Media Arts & Sciences", "Cinema and Media Studies"],
    },
  },
  "Art History": {
    unitTarget: 10,
    description:
      "Ten-unit program with ARTH 100, a studio intro, eight additional ARTH units (two at 300-level) spanning Americas, Africa/Middle East/Europe, Asia, pre-1800, and post-1800 surveys.",
    prerequisites:
      "Complete ARTH 100 and a 100-level studio course early; work with an advisor to cover geographic and chronological breadth.",
    artHistoryStructure: {
      foundation: [
        { id: "arth-foundation-arth100", label: "ARTH 100 or WRIT 107", options: ["ARTH 100", "WRIT 107"] },
        { id: "arth-foundation-studio", label: "100-level Studio", options: ["ARTS 105", "ARTS 108", "CAMS 138", "ARTS 109", "ARTS 112", "ARTS 113", "ARTS 165", "CAMS 135"] },
      ],
      regionAmericas: ["ARTH 225", "ARTH 231", "ARTH 233", "ARTH 236", "ARTH 237", "ARTH 262", "ARTH 267", "ES 267", "AFR 292", "ARTH 292", "ARTH 301", "ARTH 303", "ARTH 305", "ARTH 306", "ARTH 314", "ARTH 315", "AFR 316", "ARTH 316", "ARTH 317", "ARTH 320", "ARTH 321", "ARTH 333", "ARTH 339", "ARTH 376", "ARTH 378"],
      regionEMEA: ["ARTH 110Y", "ARTH 123", "ARTH 203", "ARTH 209", "ARTH 212", "ARTH 222", "MAS 222", "ARTH 224", "ARTH 226", "CAMS 207", "ARTH 227", "ARTH 228", "ARTH 229", "ARTH 243", "ARTH 244", "ARTH 246", "ARTH 247", "ARTH 251", "ARTH 256", "ARTH 259", "AFR 264", "ARTH 264", "ARTH 288", "ARTH 289", "ARTH 290", "ARTH 299", "ARTH 303", "ARTH 308", "ARTH 315", "ARTH 321", "ARTH 322", "ARTH 325", "ARTH 328", "ARTH 343", "ARTH 347", "ARTH 373", "CLCV 373", "ARTH 393", "WRIT 149"],
      regionAsia: ["ARTH 212", "ARTH 229", "ARTH 238", "ARTH 239", "SAS 239", "ARTH 240", "ARTH 248", "ARTH 249", "ARTH 255", "ARTH 337", "ARTH 341", "ARTH 346", "ARTH 347", "ARTH 397"],
      pre1800: ["ARTH 110Y", "ARTH 123", "ARTH 200", "ARTH 203", "ARTH 209", "ARTH 217", "ARTH 222", "MAS 222", "ARTH 227", "ARTH 229", "ARTH 233", "ARTH 236", "ARTH 238", "ARTH 239", "SAS 239", "ARTH 240", "ARTH 243", "ARTH 244", "ARTH 246", "ARTH 247", "ARTH 248", "ARTH 249", "ARTH 251", "ARTH 256", "ARTH 259", "ARTH 290", "ARTH 325", "ARTH 328", "ARTH 333", "ARTH 337", "ARTH 341", "ARTH 343", "ARTH 346", "ARTH 347", "ARTH 373", "CLCV 373", "ARTH 378", "ARTH 393"],
      post1800: ["ARTH 200", "ARTH 212", "ARTH 224", "ARTH 225", "ARTH 226", "CAMS 207", "ARTH 228", "ARTH 231", "ARTH 233", "ARTH 237", "ARTH 255", "ARTH 262", "ARTH 267", "ES 267", "ARTH 288", "ARTH 289", "AFR 292", "ARTH 292", "ARTH 301", "ARTH 303", "ARTH 308", "ARTH 314", "ARTH 315", "AFR 316", "ARTH 316", "ARTH 317", "ARTH 320", "ARTH 321", "ARTH 322", "ARTH 324", "PHIL 324", "ARTH 333", "ARTH 339", "ARTH 376", "ARTH 391", "ARTH 397"],
      level300Required: 2,
    },
  },
  Biochemistry: {
    unitTarget: 15,
    description:
      "Interdisciplinary plan spanning intro biology/chemistry/physics, core biochemistry labs, advanced BIOC/BISC/CHEM electives, and a lab/research experience.",
    prerequisites:
      "Finish the introductory science/math sequence early (BISC 110-series, CHEM 105-series, PHYS 104-series, MATH 116/120) to access BIOC core courses.",
    biocStructure: {
      foundation: [
        { id: "bioc-bisc-intro", label: "Intro Biology", options: ["BISC 110", "BISC 110P", "BISC 112", "BISC 112Y", "BISC 116"] },
        { id: "bioc-chem-intro", label: "Intro Chemistry", options: ["CHEM 105", "CHEM 105P", "CHEM 116", "CHEM 120"] },
        { id: "bioc-phys-intro", label: "Intro Physics", options: ["PHYS 104", "PHYS 106", "PHYS 107", "PHYS 108"] },
        { id: "bioc-math", label: "Calculus (MATH 116/120)", options: ["MATH 116", "MATH 120"] },
      ],
      bisc200: [
        { id: "bioc-bisc-219", label: "BIOC/BISC 219", options: ["BIOC 219", "BISC 219"] },
        { id: "bioc-bisc-220", label: "BIOC/BISC 220", options: ["BIOC 220", "BISC 220"] },
      ],
      chem200: [
        { id: "bioc-chem-120", label: "CHEM 120 or 205", options: ["CHEM 120", "CHEM 205"] },
        { id: "bioc-chem-211", label: "CHEM 211", options: ["CHEM 211"] },
        { id: "bioc-chem-223", label: "BIOC/CHEM 223", options: ["BIOC 223", "CHEM 223"] },
      ],
      bisc300Courses: ["BISC 302", "BISC 303", "BISC 311", "BISC 313", "BISC 314", "BISC 316", "BISC 318", "BISC 329", "BISC 333", "BISC 335", "BISC 336", "NEUR 332"],
      chem300Required: ["BIOC 331", "CHEM 331"],
      chem300Electives: ["CHEM 312", "BIOC 320", "CHEM 320", "BIOC 323", "CHEM 323", "BIOC 324", "CHEM 324", "BIOC 325", "CHEM 325"],
      labCourses: ["BISC 302", "BISC 311", "BISC 314", "BISC 316", "BISC 329", "BISC 333", "BIOC 320", "CHEM 320"],
      researchCourses: ["BIOC 250", "BIOC 250H", "BIOC 251", "BIOC 251H", "BIOC 350", "BIOC 350H", "BIOC 351", "BIOC 351H", "BIOC 355", "BIOC 360", "BIOC 365", "BIOC 370"],
    },
  },
  "Chemical Physics": {
    unitTarget: 12,
    description:
      "Chemistry + physics hybrid covering intro sequences, advanced lab techniques, quantum/statistical theory, and a senior physics elective.",
    prerequisites:
      "Finish calculus (MATH 215) and the CHEM/PHYS introductory sequences early to access PHYS 207/208 and upper-level labs.",
    chphStructure: {
      generalChemIntro: ["CHEM 105", "CHEM 105P", "CHEM 116"],
      generalChemSecond: ["CHEM 205"],
      generalChemAlt: ["CHEM 120"],
      physicsIntro: ["PHYS 107", "PHYS 108"],
      requiredCourses: [
        "PHYS 205",
        "MATH 215",
        "PHYS 207",
        "PHYS 208",
        "CHEM 211",
        "CHEM 341",
        "CHEM 330",
      ],
      labChoice: [
        { id: "chph-lab", label: "PHYS 210 or CHEM 361", options: ["PHYS 210", "CHEM 361"] },
      ],
      chemAdvancedOptions: ["CHEM 334", "CHEM 335"],
      physicsElectives: ["PHYS 302", "PHYS 305", "PHYS 308", "PHYS 310", "PHYS 303", "PHYS 331"],
    },
  },
  Chemistry: {
    unitTarget: 12,
    description:
      "Chemistry majors build from general chemistry through organic, physical, analytical, and research experiences, totaling 12 units across lecture, lab, physics, and math foundations.",
    prerequisites:
      "Complete calculus (MATH 205/215) and introductory physics (PHYS 104/107, plus PHYS 106/108) early to support upper-level chemistry.",
    chemStructure: {
      foundation: [
        { id: "chem-intro-sequence", label: "CHEM 105/105P/116 or 120", options: ["CHEM 105", "CHEM 105P", "CHEM 116", "CHEM 120"] },
        { id: "chem-205", label: "CHEM 205 (if not taking CHEM 120)", options: ["CHEM 205"] },
      ],
      altSequence: ["CHEM 120"],
      coreCourses: ["CHEM 211", "CHEM 212", "CHEM 330"],
      electivePool: ["CHEM 223", "CHEM 341", "CHEM 361", "CHEM 334", "CHEM 335"],
      electiveRequired: 3,
      excludedExtra300: ["CHEM 331", "CHEM 250", "CHEM 250H", "CHEM 350", "CHEM 350H", "CHEM 355", "CHEM 360", "CHEM 365", "CHEM 370"],
      additional300Required: 1,
      researchCourses: ["CHEM 250", "CHEM 250H", "CHEM 350", "CHEM 350H", "CHEM 355", "CHEM 360", "CHEM 365", "CHEM 370"],
      physicsRequirement: ["PHYS 106", "PHYS 108"],
      physicsIntro: ["PHYS 104", "PHYS 107"],
      mathRequirement: ["MATH 215", "MATH 205"],
    },
  },
  "Cinema and Media Studies": {
    unitTarget: 10,
    description:
      "Cinema & Media Studies blends global media history/theory with production practice via CAMS 201/202, a production course, themed core electives, and two advanced seminars.",
    prerequisites:
      "Complete CAMS 201 and CAMS 202 early; consult advisors about transfer/study-abroad approvals for electives or production courses.",
    camsStructure: {
      foundation: [
        { id: "cams-201", label: "CAMS 201", options: ["CAMS 201"] },
        { id: "cams-202", label: "CAMS 202", options: ["CAMS 202"] },
        { id: "cams-101", label: "CAMS 101 (if required cohort)", options: ["CAMS 101"] },
      ],
      productionCourses: ["ARTS 108", "CAMS 138", "ARTS 110", "ARTS 165", "CAMS 135", "CAMS 234", "ENG 204", "CAMS 208", "ENG 208"],
      coreCourses: [
        "AMST 245", "CAMS 245", "AMST 254", "CAMS 254", "ARTH 226", "CAMS 207", "ARTS 208", "CAMS 238", "ARTS 255", "CAMS 255", "ARTS 260", "CAMS 230", "ARTS 221", "CAMS 239", "ARTS 265", "CAMS 235", "CAMS 100", "CAMS 107Y", "CAMS 203", "CAMS 210", "CAMS 218", "CAMS 219", "CAMS 220", "CAMS 221", "CAMS 222", "CAMS 225", "CAMS 234", "CAMS 246", "CAMS 286", "GER 286", "CAMS 288", "MUS 275",
      ],
      level300Courses: [
        "ARTS 308", "CAMS 338", "ARTS 313", "CAMS 313", "ARTS 365", "CAMS 335", "ARTS 366", "CAMS 366", "CAMS 301", "CAMS 304", "CAMS 310", "CAMS 314", "CAMS 324",
      ],
      level300Required: 2,
      additionalCamsRequired: 1,
    },
  },
  "Cognitive and Linguistic Sciences": {
    unitTarget: 9,
    description:
      "Cognitive & Linguistic Sciences combines a four-course interdisciplinary core (linguistics, formal systems, PHIL 215, CLSC/PSYC 300) with a four-course concentration in linguistics, psychology, computer science, or philosophy.",
    prerequisites:
      "Work with an advisor to map the core and concentration early; a ninth course from another concentration is encouraged.",
    clscStructure: {
      core: [
        { id: "clsc-linguistics", label: "Linguistics core", dept: ["Linguistics"], prefixes: ["LING"] },
        { id: "clsc-formal", label: "Formal systems", options: ["CS 111", "CS 112", "CS 230", "MATH 215", "MATH 205", "PHIL 106", "PHIL 207"] },
        { id: "clsc-phil215", label: "PHIL 215", options: ["PHIL 215"] },
        { id: "clsc-capstone", label: "CLSC 300 / PSYC 300", options: ["CLSC 300", "PSYC 300"] },
      ],
      concentrations: [
        { id: "linguistics", label: "Linguistics", departments: ["Linguistics"], prefixes: ["LING", "CLSC"] },
        { id: "psychology", label: "Psychology", departments: ["Psychology"] },
        { id: "computerScience", label: "Computer Science", departments: ["Computer Science"] },
        { id: "philosophy", label: "Philosophy", departments: ["Philosophy"] },
      ],
      concentrationElectivesRequired: 4,
      optionalNinthAllowed: true,
    },
  },
  "Comparative Literary Studies": {
    unitTarget: 9,
    description:
      "Comparative Literary Studies spans CPLT 180, CPLT 375, and nine courses overall (≥5 CPLT). Students include one pre-1900 course and build a 3-course thematic or regional concentration.",
    prerequisites:
      "Plan concentration courses with the program director; at least one concentration course must be at the 300 level.",
    cpltStructure: {
      requiredCourses: ["CPLT 180", "CPLT 375"],
      minCpltCourses: 5,
      totalRequired: 9,
      concentrationCourses: 3,
      concentration300Required: 1,
    },
  },
  "Data Science": {
    unitTarget: 10,
    description:
      "Data Science integrates statistics, computer science, and mathematics: eight foundational courses, two advanced electives (one CS, one STAT), plus the DS capstone or thesis.",
    prerequisites:
      "Complete intro programming/statistics early; work closely with advisors to plan 300-level CS/STAT and DS 340H or DS 360/370.",
    dsStructure: {
      foundations: [
        { id: "ds-intro-stats", label: "Intro statistics", options: ["STAT 160", "STAT 218", "BISC 198", "POL 299", "PSYC 105", "ECON 103", "SOC 190"] },
        { id: "ds-qr260", label: "QR 260 / STAT 260 (or QAI)", options: ["QR 260", "STAT 260"] },
        { id: "ds-stat318", label: "STAT 318", options: ["STAT 318"] },
        { id: "ds-cs-intro", label: "Intro programming", options: ["CS 111", "CS 111M", "CS 111X", "CS 112"] },
        { id: "ds-cs230", label: "CS 230", options: ["CS 230", "CS 230X"] },
        { id: "ds-ml", label: "Advanced ML", options: ["CS 313", "CS 315", "CS 333", "CS 344", "CS 345"] },
        { id: "ds-math205", label: "MATH 205", options: ["MATH 205"] },
        { id: "ds-math206", label: "MATH 206", options: ["MATH 206"] },
      ],
      electivesCS: ["CS 231", "CS 232", "CS 234", "CS 244", "CS 248", "CS 299", "PHIL 222", "CS 313", "CS 315", "CS 331", "CS 333", "CS 344", "CS 345"],
      electivesStat: ["MATH 220", "STAT 220", "QR 309", "STAT 309", "STAT 219", "STAT 228", "STAT 320", "STAT 321", "STAT 328"],
      capstoneOptions: ["DS 340H", "DS 360", "DS 370"],
    },
  },
  "Environmental Studies": {
    unitTarget: 10,
    description:
      "Environmental Studies combines interdisciplinary core seminars, paired science requirements, a humanities-facing ES course, four electives (≥4.0 units with advanced depth), and a senior capstone.",
    prerequisites:
      "Plan introductory science with lab access early (ES 100/101/111, BISC 108/111/113, or GEOS 101) and consult your advisor on focus areas plus the ES 300/399 capstone timeline.",
    esStructure: {
      totalRequired: 10,
      coreCourses: [
        { id: "es-core-102", label: "ES 102", options: ["ES 102"] },
        { id: "es-core-214", label: "ES 214 / POL2 214", options: ["ES 214", "POL2 214"] },
      ],
      scienceIntroOptions: ["ES 100", "ES 101", "ES 111", "GEOS 101", "BISC 108", "BISC 111", "BISC 113", "BISC 116", "CHEM 103", "CHEM 116"],
      scienceCourseOptions: [
        "ES 100", "ES 101", "ES 111", "GEOS 101",
        "BISC 108", "BISC 111", "BISC 113", "BISC 116",
        "BISC 201", "BISC 202", "BISC 209", "BISC 210",
        "BISC 308", "BISC 310", "BISC 314",
        "CHEM 103", "CHEM 105", "CHEM 116", "CHEM 120",
        "GEOS 102", "GEOS 208", "GEOS 304", "GEOS 315",
      ],
      labCourses: [
        "ES 101", "ES 111", "GEOS 101",
        "BISC 108", "BISC 111", "BISC 113", "BISC 116",
        "BISC 201", "BISC 202", "BISC 209", "BISC 210",
        "BISC 308", "BISC 314",
        "CHEM 103", "CHEM 105", "CHEM 116", "CHEM 120",
        "GEOS 102", "GEOS 304", "GEOS 315",
      ],
      humanitiesManualTracking: true,
      electiveStructure: {
        creditTarget: 4,
        allowedDepartments: ["Environmental Studies"],
        allowedCourseCodes: [
          "AFR 304", "POL3 302",
          "ANTH 222",
          "ARTH 266", "ARTH 317",
          "BISC 108", "BISC 111", "BISC 113", "BISC 116",
          "BISC 198", "BISC 201", "BISC 202", "BISC 209", "BISC 210",
          "BISC 308", "BISC 310", "BISC 314",
          "CHEM 103", "CHEM 105", "CHEM 120",
          "ECON 328",
          "GEOS 102", "GEOS 208", "GEOS 304", "GEOS 315",
          "HIST 320",
          "POL4 311",
          "QR 260", "STAT 260", "STAT 160",
          "WGST 302",
        ],
        independentStudyCourses: ["ES 250", "ES 250H", "ES 350", "ES 350H", "ES 355", "ES 360", "ES 365", "ES 370", "ES 398", "ES 399H"],
        minFullCourses: 2,
        minFullCoursesLabel: "Full-unit non-independent electives",
        min300LevelFullCourses: 1,
      },
      capstoneOptions: ["ES 300", "ES 399"],
    },
  },
  "East Asian Studies": {
    unitTarget: 10,
    description:
      "East Asian Studies blends advanced language study (four 200+ courses) with humanities and history/social science coursework plus a focused concentration (three courses, two at the 300-level).",
    prerequisites:
      "Begin language study early; plan study abroad with the program director and advisor to align language, humanities, and history requirements.",
    easStructure: {
      languagePrefixes: ["CHIN", "JPN", "KOR"],
      languageRequired: 4,
      humanitiesCourses: [
        "ARTH 238", "ARTH 240", "ARTH 248", "ARTH 249", "ARTH 255", "ARTH 337", "ARTH 341", "ARTH 346",
        "CAMS 203", "CHIN 243", "CHIN 208", "CHIN 211", "CHIN 220", "CHIN 320", "CHIN 226", "CHIN 244",
        "CHIN 245", "CHIN 310", "CHIN 311", "CHIN 338", "CHIN 344", "CHIN 345", "CHIN 381", "CHIN 382",
        "CPLT 236", "EALC 236", "EALC 123", "EALC 221", "EALC 225", "EALC 325", "EALC 345",
        "JPN 251", "THST 251", "JPN 252", "JPN 280", "JPN 282", "JPN 290", "JPN 308", "JPN 314",
        "JPN 352", "JPN 358", "KOR 206", "KOR 246", "LING 246", "KOR 256", "LING 256", "REL 108",
        "REL 253", "REL 254", "REL 255", "REL 257", "REL 353",
      ],
      historyCourses: [
        "HIST 274", "HIST 277", "HIST 278", "HIST 280", "HIST 372", "HIST 395", "PEAC 119Y", "REL 119Y", "POL2 208",
      ],
      humanitiesRequired: 1,
      historyRequired: 1,
      nonLanguageRequired: 6,
      concentrationRequired: 3,
      concentration300Required: 2,
    },
  },
  "East Asian Languages and Cultures": {
    unitTarget: 8,
    description:
      "EALC majors build Chinese, Japanese, or Korean language depth (via defined sequences) alongside non-language cultural coursework and advanced seminars.",
    prerequisites:
      "Work with an advisor to plan language track, non-language surveys, and study abroad timing (EALC strongly encourages immersive study).",
    ealcStructure: {
      gateway: "EALC 221",
      tracks: {
        Chinese: {
          label: "Chinese",
          sequences: [
            ["CHIN 202", "CHIN 301", "CHIN 302"],
            ["CHIN 203", "CHIN 204", "CHIN 306"],
          ],
          seminarPrefix: "CHIN",
        },
        Japanese: {
          label: "Japanese",
          sequences: [
            ["JPN 202", "JPN 231", "JPN 232"],
          ],
          seminarPrefix: "JPN",
        },
        Korean: {
          label: "Korean",
          sequences: [
            ["KOR 202", "KOR 231", "KOR 232"],
          ],
          seminarPrefix: "KOR",
        },
      },
      nonLanguageRequired: 2,
      surveyRequired: 1,
      level300Required: 2,
    },
  },
  "Education Studies": {
    unitTarget: 9,
    description:
      "Education Studies majors blend core foundations, Education Research & Theory work, a capstone seminar or thesis, and curated electives spanning curriculum design and interdisciplinary perspectives.",
    prerequisites:
      "Plan with an advisor to decide on core starting point (EDUC 120/214/215), capstone timing (EDUC 33x or thesis), and how curriculum/elective courses support your focus area such as policy, multilingual education, or youth studies.",
    educationStructure: {
      totalRequired: 9,
      coreCourses: ["EDUC 120", "EDUC 214", "EDUC 215", "EDUC 216"],
      researchTheoryRequired: 4,
      researchTheoryCourses: [
        "AFR 205", "EDUC 205",
        "AMST 102Y", "EDUC 102Y",
        "AMST 206", "EDUC 206",
        "CHEM 302", "EDUC 317",
        "ECON 226", "EDUC 226",
        "EDUC 116Y",
        "EDUC 120",
        "EDUC 200",
        "EDUC 201",
        "EDUC 207", "SOC 207",
        "EDUC 213",
        "EDUC 214",
        "EDUC 215", "PEAC 215",
        "EDUC 222",
        "EDUC 234",
        "EDUC 236",
        "EDUC 239H", "PHYS 239H",
        "EDUC 245",
        "EDUC 252", "HIST 252",
        "EDUC 298H", "PSYC 299H",
        "EDUC 308", "SOC 308",
        "EDUC 313",
        "EDUC 321", "PEAC 312", "SOC 312",
        "EDUC 324", "PSYC 324",
        "EDUC 328", "PSYC 322",
        "EDUC 334",
        "EDUC 335",
        "EDUC 336",
        "EDUC 338",
        "EDUC 339",
        "EDUC 340",
        "EDUC 341",
        "EDUC 380",
        "EDUC 398H",
        "EDUC 399H",
        "POL4 311",
      ],
      capstoneCourses: ["EDUC 334", "EDUC 335", "EDUC 336", "EDUC 338", "EDUC 339", "EDUC 340", "EDUC 341", "EDUC 380", "EDUC 360", "EDUC 370"],
      capstoneRequired: 1,
      curriculumTeachingCourses: ["EDUC 300", "EDUC 303", "EDUC 325"],
      curriculumMax: 3,
      electiveCourses: [
        "AFR 105",
        "AFR 220",
        "AFR 249",
        "AMST 121",
        "AMST 151",
        "AMST 161",
        "AMST 222", "PSYC 222",
        "AMST 225", "SOC 225",
        "AMST 251", "SOC 251",
        "AMST 246", "SOC 246",
        "AMST 264",
        "AMST 281", "ENG 297",
        "AMST 290", "PEAC 290",
        "ANTH 210",
        "ANTH 231", "PEAC 231",
        "CLSC 216", "PSYC 216",
        "CS 121", "MAS 121",
        "CS 232",
        "ECON 241",
        "ECON 326",
        "ECON 327",
        "ENGR 305", "PEAC 305",
        "HIST 203",
        "HIST 204",
        "LING 114",
        "LING 238",
        "LING 244",
        "LING 248",
        "LING 312",
        "LING 338",
        "PEAC 104",
        "POL1 328",
        "POL4 249",
        "POL1 337",
        "POL4 341",
        "PSYC 101",
        "PSYC 207",
        "PSYC 210",
        "PSYC 217",
        "PSYC 245",
        "PSYC 307R",
        "PSYC 316",
        "PSYC 326",
        "PSYC 333",
        "PSYC 337",
        "PSYC 344",
        "SAS 232", "SOC 232",
        "SOC 205", "WGST 211",
        "SOC 209",
        "WGST 221",
        "WGST 224",
        "WGST 326",
        "MIT EC.717",
        "MIT 11.124",
        "MIT 11.125",
      ],
      electiveMax: 3,
      independentStudyCourses: ["EDUC 250", "EDUC 250H", "EDUC 350", "EDUC 350H"],
      independentStudyLimit: 1,
      education300Required: 2,
    },
  },
  Classics: {
    unitTarget: 10,
    description:
      "Classics majors complete six units split between Greek and Latin (≥2 at 300-level) plus four civilization courses spanning history, literature, and material culture.",
    prerequisites:
      "Work with an advisor to balance Greek and Latin; plan early for study abroad opportunities in Rome or Athens.",
    classicsStructure: {
      languageTotalRequired: 6,
      languageMinUpper: 2,
      languageMaxIntro: 2,
      civRequired: 4,
      civClcvRequired: 2,
      civMax100: 1,
      civCourseCodes: [
        "ANTH 103", "CLCV 103", "ARTH 203", "ARTH 243", "ARTH 290", "ARTH 343", "ARTH 373", "ARTH 393",
        "HIST 200", "HIST 228", "HIST 229", "HIST 230", "HIST 231", "HIST 325",
        "PHIL 201", "PHIL 305",
        "REL 104", "REL 105", "REL 243", "REL 244",
      ],
    },
  },
  "Media Arts and Sciences": {
    unitTarget: 12,
    introductoryCourses: {
      visualAnalysis: ["ARTH 100", "WRIT 107", "CAMS 100"],
      studioFoundation: ["Any 100-level ARTS course"],
      computerScience: ["Any 100-level CS course"],
    },
    coreCourses: {
      studioCore: [
        "ARTS 205",
        "ARTS 207",
        "ARTS 208",
        "ARTS 216",
        "ARTS 219",
        "ARTS 220",
        "ARTS 221",
        "ARTS 222",
        "ARTS 223",
        "ARTS 255",
        "ARTS 260",
        "ARTS 265",
        "ARTS 307",
        "ARTS 308",
        "ARTS 313",
        "ARTS 317H",
        "ARTS 318H",
        "ARTS 321",
        "ARTS 322",
        "ARTS 323",
        "ARTS 336",
        "ARTS 365",
        "ARTS 366",
        "CAMS 301",
        "MUS 275",
        "MUS 277",
      ],
      csCore: [
        "CS 110",
        "CS 111",
        "CS 121",
        "CS 200",
        "CS 204",
        "CS 220",
        "CS 221",
        "CS 230",
        "CS 232",
        "CS 304",
        "CS 307",
        "CS 315",
        "CS 317",
        "CS 320",
        "CS 321",
        "CS 323",
        "CS 325",
        "CS 365",
        "CS 366",
      ],
    },
    capstoneRequired: 1,
    capstoneCourses: ["ARTS 321", "ARTS 322", "ARTS 365", "ARTS 366", "CS 365", "CS 366"],
    mediaCulture: 1,
    advancedProduction: 1,
    portfolioRequired: true,
    description:
      "Interdisciplinary major combining studio arts, computer science, and media culture. Requires 3 intro courses, 6 core courses (3 studio + 3 CS), 1 capstone, and portfolio.",
  },
  "Africana Studies": {
    unitTarget: 9,
    description:
      "Nine-course Africana Studies major anchored by AFR 105 (or AFR 210 for late declarers), with at least two 300-level AFR seminars, attendance at the Africana Colloquium, and a chosen geographic or thematic concentration across the Africana world.",
    afrStructure: {
      introOptions: ["AFR 105", "AFR 210"],
      level300Required: 2,
    },
  },
  "American Studies": {
    unitTarget: 9,
    description:
      "Interdisciplinary major examining the histories and cultures of the United States through American Studies coursework, electives drawn from affiliated departments, and an advisor-approved thematic concentration.",
    amerStructure: {
      introOptions: ["AMST 101", "AMST 121"],
      coreCoursesRequired: 5,
      level300Required: 2,
      electiveCoursesRequired: 3,
    },
  },
  French: {
    unitTarget: 9,
    description:
      "The French major requires a minimum of nine semester courses above FREN 201, including FREN 210, FREN 211 or FREN 212, and at least two 300-level courses taught in French (one in senior year). One course may be taught in English in the French Department.",
    prerequisites:
      "Complete FREN 101, FREN 102, and FREN 201 (these count toward degree but not major). Take the French placement test if you have prior French experience. Students are strongly encouraged to study abroad in France or a Francophone country.",
    frenchStructure: {
      totalRequired: 9,
      above201Required: 9,
      foundationOptions: ["FREN 210", "FREN 211", "FREN 212"],
      foundationRequired: 1,
      level300Required: 2,
      level300InFrenchRequired: 2,
      seniorYear300Required: 1,
      englishCourseMax: 1,
      excludedCourses: ["FREN 350", "FREN 360", "FREN 370"],
      creditNonCreditMax: 2,
    },
  },
  "French Cultural Studies": {
    unitTarget: 8,
    description:
      "Interdepartmental major combining French language and culture with courses from other departments. Requires four French units above FREN 201 including FREN 207 and one foundation course, plus two 300-level French courses.",
    prerequisites:
      "Work with two advisors (one from French, one from another department). Courses from Africana Studies, Art, History, Music, Political Science, and other departments may count toward the major.",
    frenchCulturalStructure: {
      totalRequired: 8,
      frenchUnitsRequired: 4,
      above201Required: 4,
      requiredCourses: ["FREN 207"],
      foundationOptions: ["FREN 210", "FREN 211", "FREN 212"],
      foundationRequired: 1,
      level300Required: 2,
      otherDepartmentUnits: 4,
      excludedCourses: ["FRST 350", "FRST 360", "FRST 370"],
      creditNonCreditMax: 2,
    },
  },
  "Italian Studies": {
    unitTarget: 9,
    description:
      "Nine units above the 100 level including one foundation course and two 300-level courses in the department. One course may be taken outside the department on a related topic. Courses in translation count toward the major.",
    prerequisites:
      "Students are strongly urged to begin Italian in first year. ITAS 101, ITAS 102, ITAS 103 count toward degree but not major. Qualified students are encouraged to study abroad in Italy.",
    italianStructure: {
      totalRequired: 9,
      above100Required: 9,
      foundationOptions: ["ITAS 209", "ITAS 210", "ITAS 220", "ITAS 272"],
      foundationRequired: 1,
      level300Required: 2,
      level300InDeptRequired: 2,
      outsideDepartmentMax: 1,
      excludedCourses: ["ITAS 350", "ITAS 360", "ITAS 370"],
      creditNonCreditMax: 2,
      translationCoursesAllowed: true,
    },
  },
  Geosciences: {
    unitTarget: 12,
    description:
      "Twelve courses total: three core requirements (100-200 level), five electives (three at 300-level, one must be Wellesley 300-level with lab), and four cognate STEM courses (two from same discipline). Maximum two approved courses from outside Wellesley.",
    prerequisites:
      "Complete one 100-level course (GEOS 101 or GEOS 102) and two 200-level courses (GEOS 200/200X and GEOS 203). Choose areas of focus like Earth Materials, Tectonics, Environmental Geosciences, or Surface Processes.",
    geosciencesStructure: {
      totalRequired: 12,
      coreRequired: 3,
      core100Options: ["GEOS 101", "GEOS 102"],
      core200Required: ["GEOS 200", "GEOS 200X", "GEOS 203"],
      electivesRequired: 5,
      level300ElectivesRequired: 3,
      level300WellesleyWithLabRequired: 1,
      cognateSTEMRequired: 4,
      cognateSameDisciplineRequired: 2,
      outsideWellesleyMax: 2,
      allowedCognateDisciplines: ["Mathematics", "Biological Sciences", "Chemistry", "Physics", "Astronomy", "Computer Science", "Environmental Studies"],
      excludedCourses: ["GEOS 350", "GEOS 360", "GEOS 370"],
    },
  },
  "German Studies": {
    unitTarget: 9,
    description:
      "Individual structured major combining advanced German language with cultural studies. Nine courses including German courses above GER 102 and related English-taught courses, developed in consultation with advisor.",
    prerequisites:
      "Work closely with major advisor or Department Chair to develop individualized plan. Combine advanced fluency with emphasis on specific components of media, history, culture, and society.",
    germanStructure: {
      totalRequired: 9,
      aboveGER102Required: 6,
      englishTaughtAllowed: 3,
      focusAreas: ["Media", "History", "Culture", "Society"],
      individualized: true,
    },
  },
  History: {
    unitTarget: 9,
    description:
      "Nine units including two 300-level courses (one must be seminar). Must include one non-Western course, one Western course, and one premodern course. Seven units must be taken at Wellesley.",
    prerequisites:
      "Design program with breadth and depth. Consider focusing on geographical area, time period, historical approach, or specific theme. AP/IB credits do not count toward major.",
    historyStructure: {
      totalRequired: 9,
      wellesleyRequired: 7,
      level300Required: 2,
      seminarRequired: 1,
      nonWesternRequired: 1,
      westernRequired: 1,
      premodernRequired: 1,
      outsideFieldMax: 1,
      crossListedMax: 1,
      nonWesternOptions: ["Africa", "China", "Japan", "Latin America", "Middle East", "South Asia"],
      westernOptions: ["Europe", "United States", "Russia"],
      excludedCourses: ["HIST 350", "HIST 360", "HIST 370"],
    },
  },
  "Jewish Studies": {
    unitTarget: 9,
    description:
      "Nine courses including JWST 102/REL 102, two 300-level courses, four concentration courses (one 300-level), and language proficiency equivalent to two semesters intermediate level. Up to three outside courses allowed.",
    prerequisites:
      "Take Introduction to Jewish Studies by end of junior year. Develop concentration in area like religion, European Jewish history, American Jewish studies, or Sephardic studies. Show language proficiency in Hebrew, Yiddish, Ladino, or relevant language.",
    jewishStudiesStructure: {
      totalRequired: 9,
      requiredCourse: "JWST 102",
      alternateRequired: "REL 102",
      level300Required: 2,
      concentrationRequired: 4,
      concentration300Required: 1,
      languageRequired: 2,
      outsideWellesleyMax: 3,
      languageOptions: ["Hebrew", "Yiddish", "Ladino", "Arabic", "French", "Spanish", "German"],
      concentrationAreas: ["Religion", "European Jewish History", "American Jewish Studies", "Sephardic Studies", "Biblical Studies", "Hebrew Literature", "Israel Studies"],
    },
  },
  "Latin American Studies": {
    unitTarget: 9,
    description:
      "Nine-course, three-department plan centered on advanced Spanish or Portuguese, two regional surveys, and a balanced mix of humanities and social science electives focused on Latin America.",
    prerequisites:
      "Consult both a faculty advisor and the Director of Latin American Studies before declaring. Language work should reach SPAN 241+ or PORT 241+, and majors are strongly encouraged to spend a semester in Latin America. Honors is by thesis plus oral exam (normally GPA ≥3.5 in the major).",
    lasStructure: {
      outcomes: [
        "Speak and comprehend Spanish or Portuguese at an advanced ACTFL level.",
        "Demonstrate foundational knowledge of Latin American history, cultures, economies, and literatures.",
        "Show disciplinary breadth in at least one social science and one humanities field.",
        "Compare and critique methods across at least three disciplines in the social sciences and humanities.",
        "Apply disciplinary methods to synthesize research and complete original work on Latin American topics.",
        "Present findings in clear writing and oral presentations.",
      ],
      languageRequirement: "Two language units at SPAN 241+ or PORT 241+.",
      surveyCourses: [
        "ANTH 245", "LAST 245", "ECON 241", "LAST 241", "HIST 207", "LAST 207",
        "HIST 211", "LAST 211", "LAST 101", "LAST 217", "POL2 207", "LAST 275", "SPAN 275",
        "MIT 17.55J", "MIT 21H.171",
      ],
      electiveRules: {
        totalElectives: 5,
        humanities: 2,
        humanities300: 1,
        socialScience: 2,
        socialScience300: 1,
      },
      humanitiesCourses: [
        "AFR 242 / REL 214", "AFR 256 / PORT 256", "ARTH 233", "ARTH 234", "ARTH 236", "ARTH 378",
        "CAMS 240 / WGST 240", "LAST 221H", "PORT 241", "SPAN 251", "SPAN 257", "SPAN 279",
        "SPAN 303", "SPAN 309", "SPAN 329", "SPAN 335",
      ],
      socialScienceCourses: [
        "AFR 299", "AFR 341", "AMST 225 / SOC 225", "AMST 290 / PEAC 290", "AMST 323",
        "ANTH 231 / PEAC 231", "ANTH 245 / LAST 245", "ANTH 346", "ECON 241 / LAST 241",
        "EDUC 321 / PEAC 312 / SOC 312", "HIST 206", "HIST 207 / LAST 207", "HIST 211 / LAST 211",
        "HIST 218", "HIST 357", "HIST 358", "HIST 376", "HIST 377", "LAST 217 / POL2 207",
        "POL4 345",
      ],
      paperFlagHumanities: ["AFR 242"],
      paperFlagSocial: ["AFR 341", "AMST 225", "SOC 225", "ANTH 231", "PEAC 231", "ANTH 346", "EDUC 321", "PEAC 312", "SOC 312", "HIST 244", "POL4 345"],
      honorsNote:
        "Honors requires a thesis on Latin America plus an oral exam. Candidates normally need ≥3.5 GPA in the major; petitions for 3.0–3.5 considered.",
      studyAbroadNote:
        "Study in Latin America is strongly encouraged (e.g., Wellesley-in-Chile). Director approval required for transfer credit; courses abroad rarely transfer at the 300 level.",
    },
  },
  "Medieval/Renaissance Studies": {
    unitTarget: 9,
    description:
      "Interdisciplinary nine-course major spanning history, art history, religion, literature, philosophy, music, and book studies. At least four courses must be above the 100 level in a concentration, with two 300-level courses typically taken at Wellesley.",
    prerequisites:
      "Select an advisor in your area of concentration and map the advanced work early. Credit/noncredit courses and AP credits do not count. Normally no more than two courses from outside Wellesley count toward the major (up to three from accredited programs abroad).",
    merStructure: {
      goals: [
        "Integrate coursework across humanities disciplines for a unified view of the Middle Ages and Renaissance.",
        "Show familiarity with foundational works and events of the era.",
        "Analyze primary/secondary sources and build sophisticated arguments.",
        "Conduct original research and articulate cultural unity/diversity across Europe and the Mediterranean.",
        "Reach depth in at least one disciplinary or thematic specialization.",
      ],
      concentrationAbove100: 4,
      level300Required: 2,
      coursePool: [
        "ARTH 110Y", "ARTH 222", "ARTH 227", "ARTH 229", "ARTH 244", "ARTH 246", "ARTH 247", "ARTH 251",
        "ARTH 299", "ARTH 325", "ARTH 328", "ARTH 331", "ARTH 347", "ARTH 348", "CPLT 247 / ENG 247 / MER 247",
        "CHIN 211", "CHIN 220", "ENG 112", "ENG 210", "ENG 212 / MER 212", "ENG 213", "ENG 221 / HIST 221",
        "ENG 222", "ENG 223", "ENG 224", "ENG 227", "ENG 315", "ENG 317", "ENG 324", "ENG 325",
        "FREN 210", "FREN 217", "FREN 224", "FREN 303", "FREN 333", "HIST 208", "HIST 211 / LAST 211",
        "HIST 213", "HIST 214", "HIST 222", "HIST 232", "HIST 234", "HIST 246", "HIST 279", "HIST 352",
        "HIST 354", "HIST 358", "HIST 379", "ITAS 263", "MES 261 / REL 261", "MES 271 / REL 271",
        "MES 359 / REL 359", "MES 363 / REL 363", "MES 365 / REL 365", "MES 367 / REL 367", "MES 371 / REL 371",
        "MUS 200", "PHIL 200", "PHIL 221", "PHIL 325", "REL 262", "REL 270", "SPAN 241", "SPAN 252", "SPAN 278",
        "SPAN 302", "SPAN 307", "SPAN 308", "SPAN 311", "SPAN 318", "SPAN 325", "WRIT 147", "WRIT 149",
        "WRIT 167", "WRIT 172",
      ],
      honorsNote:
        "Honors is by thesis plus oral exam; admission normally requires ≥3.5 GPA in the major (petitions considered for 3.0–3.5).",
      studyAbroadNote:
        "Substitute up to two courses from outside Wellesley toward the major (up to three from accredited programs abroad); required 300-level work should be taken at Wellesley.",
    },
  },
  "Middle Eastern Studies": {
    unitTarget: 9,
    description:
      "Nine-unit major built around Arabic (or approved language), four upper-level courses in a focused area, and at least two 300-level courses (normally including a seminar).",
    prerequisites:
      "Demonstrate Arabic proficiency at the second-year level (or approved substitute language with director’s written approval). No credit is given for first-year language study. Up to two courses taken away from Wellesley may count (third by petition).",
    mesStructure: {
      goals: [
        "Demonstrate knowledge of Middle Eastern and North African histories, cultures, and religious traditions.",
        "Apply linguistic skills and disciplinary methods for advanced study.",
        "Develop an in-depth field (e.g., Arabic literature, art/architecture, religion, modern Middle East, gender).",
        "Formulate arguments, test hypotheses, and write with clarity across departments contributing to MES.",
      ],
      languagePrefixes: ["ARAB"],
      altLanguages: ["Persian", "Turkish", "Hebrew"],
      concentrationCoursesRequired: 4,
      level300Required: 2,
      seminarRequired: 1,
      coursePool: [
        "ARAB 310 / MES 310", "ARTH 203", "ARTH 247", "ARTH 348", "CPLT 275", "CPLT 364 / HIST 364 / MES 364",
        "CPLT 375", "HIST 266 / SAS 266", "HIST 268", "HIST 284", "HIST 293 / MES 293", "HIST 365 / MES 368",
        "HIST 366 / MES 366", "HIST 367 / SAS 367", "HIST 369 / MES 369", "JWST 104 / REL 104", "MES 261 / REL 261",
        "MES 262 / REL 262", "MES 263 / REL 263", "MES 267 / REL 267", "MES 270H", "MES 271 / REL 271",
        "MES 280 / REL 270", "MES 312", "MES 347 / REL 347", "MES 358 / PEAC 358 / POL2 359", "MES 359 / REL 359",
        "MES 361 / REL 361", "MES 363 / REL 363", "MES 365 / REL 365", "MES 367 / REL 367", "MES 371 / REL 371",
        "PEAC 217 / POL2 217", "PEAC 330 / REL 330", "REL 105", "REL 242", "REL 243", "REL 244", "REL 342",
        "REL 345", "SPAN 252",
      ],
      honorsNote:
        "Honors is by thesis plus oral exam; admission normally requires ≥3.5 GPA in the major (petitions considered for 3.0–3.5).",
      awayCoursePolicy:
        "Two approved courses away from Wellesley may count toward the major; a third requires petition with advisor support.",
    },
  },
  Music: {
    unitTarget: 10,
    description:
      "Ten-unit program integrating theory, history/culture/composition, performance, ensembles, and a culminating project. Includes two years of ensemble participation and a capstone seminar.",
    prerequisites:
      "Complete the Music Theory Placement Evaluation to determine if MUS 100 and MUS 122 are needed. Ensemble participation begins early; AP/IB credit does not count toward the major.",
    musicStructure: {
      outcomes: [
        "Develop musical literacy, aural skills, and contextual understanding across traditions.",
        "Write and speak about music with a scholarly voice; compose or create sound work.",
        "Identify, analyze, and interpret diverse musical styles and traditions.",
        "Build collaborative skills through ensembles and performance.",
        "Use music for advocacy and community engagement.",
      ],
      newRequirements: {
        theoryRequired: 3,
        theoryCourses: ["MUS 100", "MUS 122", "MUS 220", "MUS 252", "MUS 315"],
        historyCultureRequired: 4,
        historyCultureCourses: ["MUS 200", "MUS 201", "MUS 202", "MUS 210", "MUS 245", "MUS 276", "MUS 277", "MUS 275", "MUS 209", "MUS 309", "MUS 398"],
        electiveRequired: 1,
        electiveExamples: ["MUS 100", "MUS 122", "ITAS 223 / MUS 223", "MUS 250", "MUS 350", "MUS 275", "AMST 217", "year-long lessons (MUS 149/199/249/299/344)"],
        capstoneRequired: 1,
        capstoneCourses: ["MUS 300", "MUS 301"],
        ensembleRequired: 1,
        ensembleCourses: ["MUS 260", "MUS 270"],
        culminatingOptions: ["Honors thesis (Program I)", "Composition/sound art project (Program II)", "Performance project (Program III)"],
      },
      legacyTracks: [
        {
          title: "Western Classical Music",
          summary: "MUS 122, MUS 252, MUS 200/201/202, MUS 315, MUS 300/301, three electives (one may be MUS 100 or a full year of lessons).",
        },
        {
          title: "Jazz and World Music",
          summary: "MUS 209/309, MUS 220, MUS 245/345, two of MUS 200/201/202/210, MUS 276, MUS 398, two electives (e.g., MUS 100, MUS 122, ITAS 223/MUS 223, MUS 250/350/275, AMST 217), MUS 300/301.",
        },
        {
          title: "Digital Media / Experimental Music",
          summary: "MUS 122, MUS 202, MUS 275, MUS 277, CS 111, one CAMS and one MAS course, two electives (one may be MUS 100), MUS 300/301.",
        },
      ],
      ensembleNote:
        "Two academic years of ensemble participation (MUS 260 or MUS 270) are required for all concentrations.",
    },
  },
  "Custom Major": {
    description:
      "Design an interdepartmental plan that is not covered by Wellesley's existing majors. An individual major should build cumulative expertise around a clearly described theme, blend theoretical and methodological work, and include at least eight units above the introductory level (minimum four in a single department).",
    prerequisites:
      "Draft the plan with two faculty advisors from different departments and submit it to the Committee on Curriculum and Academic Policy (CCAP) for approval—ideally by sophomore spring. Use the Major Declaration form on MyWellesley once the plan is approved, and route later changes through your advisors and CCAP.",
  },
};
